# Generated by Django 3.1.6 on 2021-02-10 04:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 10, 4, 29, 49, 788787), verbose_name='Workout Time'),
        ),
    ]
