# Generated by Django 3.1.6 on 2021-02-10 04:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_auto_20210210_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 10, 4, 51, 18, 61744), verbose_name='Workout Time'),
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('calories', models.IntegerField()),
                ('meal', models.CharField(max_length=100)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 10, 4, 51, 18, 62134), verbose_name='Meal Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
