# Generated by Django 3.1.6 on 2021-02-10 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210210_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 10, 5, 36, 38, 414004), verbose_name='Meal Time'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 10, 5, 36, 38, 413524), verbose_name='Workout Time'),
        ),
    ]
